/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Doctor;

import Business.Components.Prescription;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.CovidCareCenter;
import Business.Organization.CovidTest;
import Business.Organization.Doctor;
import Business.Organization.Organization;
import Business.Organization.Patient;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import com.finalproject.finalproject.LoginPanel;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Skanda
 */
public class DoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorPanel
     */
    EcoSystem system;
    UserAccount account;
    Doctor doc;
    Patient pat;
    CovidCareCenter hosp;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public DoctorPanel(EcoSystem system, UserAccount account) {
        initComponents();
        this.system = system;
        this.account = account;
        doc = null;
        Network net=null;
        for (Network n : system.getNetworkMap().values()) {
            for (Organization o : n.getCovidCare().getOrganizationDirectory().getOrgList()) {
                if (o.getType().equals(Organization.Type.CovidCareCenter)) {
                    CovidCareCenter c = (CovidCareCenter) o;
                    for (Doctor d : c.getDoctorList()) {
                        if (d.getUser().getUserName().equals(account.getUserName())) {
                            doc = d;
                            net = n;
                        }
                    }
                }
            }
        }
        populateTable();
        for(PharmacyOrganization ph:net.getCovidCare().getPharmacies()){
            pharmBox.addItem(ph);
        }
        lblTitle.setText("Welcome Doctor, " + doc.getFullName());
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        model.setRowCount(0);

        for (Patient pat : doc.getPatientList()) {
            model.addRow(new Object[]{pat, pat.getPatientId(), pat.getNetwork().getName(), pat.getCovidStatus()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTest = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtprescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        finishAppointments = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pharmBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        lblTitle.setBackground(new java.awt.Color(0, 184, 148));
        lblTitle.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("WELCOME, DOCTOR");
        lblTitle.setOpaque(true);

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Network", "Covid Status"
            }
        ));
        jScrollPane1.setViewportView(patientTable);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient List:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Order Covid Test?");

        txtTest.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTest.setForeground(new java.awt.Color(255, 255, 255));
        txtTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Needed", "PCR", "Antigen" }));

        txtprescription.setColumns(20);
        txtprescription.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtprescription.setRows(5);
        jScrollPane2.setViewportView(txtprescription);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Prescription:");

        finishAppointments.setBackground(new java.awt.Color(0, 184, 148));
        finishAppointments.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        finishAppointments.setText("FINISH APPOINTMENT");
        finishAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishAppointmentsActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(211, 84, 0));
        jButton1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pharmBox.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pharmBox.setForeground(new java.awt.Color(255, 255, 255));
        pharmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmBoxActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Select Pharmacy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pharmBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                            .addComponent(finishAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(310, 310, 310)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pharmBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(61, 61, 61)
                .addComponent(finishAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void finishAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishAppointmentsActionPerformed
        // TODO add your handling code here:'
         DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
            int row = patientTable.getSelectedRow();
            pat = (Patient) model.getValueAt(row, 0);
        if (!(txtTest.getSelectedItem().toString().equals("Not Needed"))) {
            System.out.println("Covid test Creation taking place");
            String testType = txtTest.getSelectedItem().toString();
            CovidTest test = new CovidTest(pat, doc, doc.getCareCenter());
            test.setType(txtTest.getSelectedItem().toString());     
            test.setOrderedDate(new Date());
            test.setOutcome("Pending");
            test.setReferringDoctor(doc);
            test.setReferringHospital(doc.getCareCenter());
            pat.getTests().add(test);
            doc.getCareCenter().getCovidTests().add(test);
        }
        if (!txtprescription.getText().equals("")) {
            Prescription pres = new Prescription(new Date(), txtprescription.getText(),doc, (PharmacyOrganization) pharmBox.getSelectedItem());
            pat.getPrescriptions().add(pres);
            doc.getCareCenter().getPrescriptions().add(pres);
            PharmacyOrganization pharm = (PharmacyOrganization) pharmBox.getSelectedItem();
            pharm.getPrescriptions().add(pres);
        }
            pat.setActiveAppointment(false);
            pat.setAppointmentStatus("No Upcoming Appointment");
            doc.getPatientList().remove(pat);
            populateTable();
    }//GEN-LAST:event_finishAppointmentsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.setContentPane(new LoginPanel(this.system));
        topFrame.revalidate();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pharmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishAppointments;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable patientTable;
    private javax.swing.JComboBox<PharmacyOrganization> pharmBox;
    private javax.swing.JComboBox<String> txtTest;
    private javax.swing.JTextArea txtprescription;
    // End of variables declaration//GEN-END:variables
}
