/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Doctor;

import Business.Components.Prescription;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.CovidCareCenter;
import Business.Organization.CovidTest;
import Business.Organization.Doctor;
import Business.Organization.Organization;
import Business.Organization.Patient;
import Business.UserAccount.UserAccount;
import com.finalproject.finalproject.LoginPanel;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Skanda
 */
public class DoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorPanel
     */
    EcoSystem system;
    UserAccount account;
    Doctor doc;
    Patient pat;
    CovidCareCenter hosp;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public DoctorPanel(EcoSystem system, UserAccount account) {
        initComponents();
        this.system = system;
        this.account = account;
        doc = null;
        for (Network n : system.getNetworkMap().values()) {
            for (Organization o : n.getCovidCare().getOrganizationDirectory().getOrgList()) {
                if (o.getType().equals(Organization.Type.CovidCareCenter)) {
                    CovidCareCenter c = (CovidCareCenter) o;
                    for (Doctor d : c.getDoctorList()) {
                        if (d.getUser().getUserName().equals(account.getUserName())) {
                            doc = d;
                        }
                    }
                }
            }
        }
        populateTable();
        lblTitle.setText("Welcome Doctor, " + doc.getFullName());
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        model.setRowCount(0);

        for (Patient pat : doc.getPatientList()) {
            model.addRow(new Object[]{pat, pat.getPatientId(), pat.getNetwork().getName(), pat.getCovidStatus()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTest = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtprescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        finishAppointments = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Welcome,Doctor");

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Network", "Covid Status"
            }
        ));
        jScrollPane1.setViewportView(patientTable);

        jLabel2.setText("Patient List:");

        jLabel3.setText("Order Covid Test?");

        txtTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Needed", "PCR", "Antigen" }));

        txtprescription.setColumns(20);
        txtprescription.setRows(5);
        jScrollPane2.setViewportView(txtprescription);

        jLabel4.setText("Prescription:");

        finishAppointments.setText("Finish Appointment");
        finishAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishAppointmentsActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(finishAppointments)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finishAppointments))
                .addGap(0, 54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void finishAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishAppointmentsActionPerformed
        // TODO add your handling code here:'
         DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
            int row = patientTable.getSelectedRow();
            pat = (Patient) model.getValueAt(row, 0);
        if (!(txtTest.getSelectedItem().toString().equals("Not Needed"))) {
            System.out.println("Covid test Creation taking place");
            String testType = txtTest.getSelectedItem().toString();
            CovidTest test = new CovidTest(pat, doc, doc.getCareCenter());
            test.setType(txtTest.getSelectedItem().toString());     
            test.setOrderedDate(new Date());
            test.setOutcome("Pending");
            test.setReferringDoctor(doc);
            test.setReferringHospital(doc.getCareCenter());
            pat.getTests().add(test);
            doc.getCareCenter().getCovidTests().add(test);
        }
        if (!txtprescription.getText().equals("")) {
            Prescription pres = new Prescription(new Date(), txtprescription.getText(), doc);
            pat.getPrescriptions().add(pres);
            doc.getCareCenter().getPrescriptions().add(pres);
            
        }
            pat.setActiveAppointment(false);
            doc.getPatientList().remove(pat);
            populateTable();
    }//GEN-LAST:event_finishAppointmentsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.setContentPane(new LoginPanel(this.system));
        topFrame.revalidate();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishAppointments;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable patientTable;
    private javax.swing.JComboBox<String> txtTest;
    private javax.swing.JTextArea txtprescription;
    // End of variables declaration//GEN-END:variables
}
