/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Patient;

import Business.Components.Prescription;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.CovidTest;
import Business.Organization.Patient;
import Business.UserAccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Skanda
 */
public class CovidTests extends javax.swing.JPanel {

    /**
     * Creates new form CovidTests
     */
    EcoSystem system;
    UserAccount ua;
    Patient pat;
    public CovidTests() {
        initComponents();
        this.system = system;
        this.ua = ua;
        pat= null;
        for (Network net : system.getNetworkMap().values()) {
            for (Patient p : net.getPatientDirectory().getPatients()) {
                if (p.getUser().equals(ua)) {
                    pat = p;
                }
            }
        }
        populateTable();
    }
    
public void populateTable(){
       DefaultTableModel model = (DefaultTableModel)testTable.getModel();
       model.setRowCount(0);
       for(CovidTest c:pat.getTests()){
           model.addRow(new Object[]{c.getOrderedDate(),c.getType(),c.getReferringHospital(),c.getOutcome()});          
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();

        jLabel1.setBackground(new java.awt.Color(0, 184, 148));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIEW COVID TESTS");
        jLabel1.setOpaque(true);

        testTable.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        testTable.setForeground(new java.awt.Color(255, 255, 255));
        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date Taken", "Test Type", "Testing Hospital", "Result"
            }
        ));
        jScrollPane1.setViewportView(testTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable testTable;
    // End of variables declaration//GEN-END:variables
}
