/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.VaccineSite;

import Business.Components.VaccineSupplyRequest;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.CovidCareCenter;
import Business.Organization.Organization;
import Business.Organization.VaccineSiteOrganization;
import Business.Organization.VaccineSupplierOrganization;
import Business.UserAccount.UserAccount;
import JxMaps.main.MapMarker;
import JxMaps.main.Modal.LatLong;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Skanda
 */
public class SupplyRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplyRequestPanel
     */
    EcoSystem system;
    UserAccount ua;
    VaccineSiteOrganization org;

    public SupplyRequestPanel(EcoSystem system, UserAccount ua) {
        initComponents();
        this.system = system;
        this.ua = ua;
        networkBox.removeAllItems();
        for(Network n:system.getNetworkMap().values()){
            networkBox.addItem(n);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkBox = new javax.swing.JComboBox<>();
        supplierLocation = new javax.swing.JButton();
        vaccineBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDoses = new javax.swing.JTextField();
        supplyReq = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(0, 184, 148));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUPPLY REQUESTs");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Network:");

        networkBox.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        supplierLocation.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        supplierLocation.setForeground(new java.awt.Color(255, 255, 255));
        supplierLocation.setText("View Suppliers");
        supplierLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierLocationActionPerformed(evt);
            }
        });

        vaccineBox.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        vaccineBox.setForeground(new java.awt.Color(255, 255, 255));
        vaccineBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "Moderna", "J&J" }));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vaccine:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Doses Required");

        txtDoses.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        supplyReq.setBackground(new java.awt.Color(0, 184, 148));
        supplyReq.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        supplyReq.setForeground(new java.awt.Color(255, 255, 255));
        supplyReq.setText("Make Supply Request");
        supplyReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplyReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vaccineBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDoses, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(supplyReq, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(supplierLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(networkBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(networkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(supplierLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaccineBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDoses, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(supplyReq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supplyReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplyReqActionPerformed
        // TODO add your handling code here:

        Network n = (Network) networkBox.getSelectedItem();
        for (Organization o : n.getVaxCenter().getOrganizationDirectory().getOrgList()) {
            if (o.getType().equals(Organization.Type.VaccineSite) && o.getUser().equals(ua)) {
                org = (VaccineSiteOrganization) o;
            }
        }
        VaccineSupplyRequest request = new VaccineSupplyRequest(vaccineBox.getSelectedItem().toString(), txtDoses.getText(), org);
        Network net = (Network) networkBox.getSelectedItem();
        LatLong tempLoc = system.getTempLocation();
        if (tempLoc == null) {
            JOptionPane.showMessageDialog(this, "Please set a valid location", "Create fail", JOptionPane.ERROR_MESSAGE);
        } else {
            VaccineSupplierOrganization co = null;
            for (VaccineSupplierOrganization o : net.getVaxCenter().getSuppliers()) {
                if (o.getLocation().equals(system.getTempLocation())) {
                    co = o;
                }
            }
            co.getRequests().add(request);
            JOptionPane.showMessageDialog(this, "Supply Request Sent", "Create Success", JOptionPane.INFORMATION_MESSAGE);
            system.setTempLocation(null);
        }
    }//GEN-LAST:event_supplyReqActionPerformed

    private void supplierLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierLocationActionPerformed
        // TODO add your handling code here:
        Network n = (Network) networkBox.getSelectedItem();
        for (Organization o : n.getVaxCenter().getOrganizationDirectory().getOrgList()) {
            if (o.getType().equals(Organization.Type.VaccineSite) && o.getUser().equals(ua)) {
                org = (VaccineSiteOrganization) o;
            }
        }
        Network net = (Network) networkBox.getSelectedItem();
        List<LatLong> coordinateList = new ArrayList<>();
        for (VaccineSupplierOrganization o : net.getVaxCenter().getSuppliers()) {
            coordinateList.add(o.getLocation());
        }
        MapMarker map = new MapMarker();
        map.setMapMarkers(coordinateList, system);

    }//GEN-LAST:event_supplierLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<Network> networkBox;
    private javax.swing.JButton supplierLocation;
    private javax.swing.JButton supplyReq;
    private javax.swing.JTextField txtDoses;
    private javax.swing.JComboBox<String> vaccineBox;
    // End of variables declaration//GEN-END:variables
}
