/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Signup;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Organization.Patient;
import Business.UserAccount.UserAccount;
import Business.Utils.Email;
import JxMaps.main.MapMarker;
import JxMaps.main.Modal.LatLong;
import Role.PatientRole;
import com.finalproject.finalproject.LoginPanel;
import com.github.javafaker.service.FakeValuesService;
import com.github.javafaker.service.RandomService;
import com.github.sarxos.webcam.Webcam;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.Locale;
import java.util.Random;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Skanda
 */
public class SignupPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignupPanel
     */
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public SignupPanel(EcoSystem system) {
        initComponents();
        this.system = system;

        for (Network n : system.getNetworkMap().values()) {
            networkBox.addItem(n);
        }
        FakeValuesService fakeValuesService = new FakeValuesService(
                new Locale("en-GB"), new RandomService());

        String prefix = fakeValuesService.bothify("??##");

        txtId.setText("#" + prefix + String.valueOf(new Random().nextInt(1000000)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        networkBox = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        snap = new javax.swing.JButton();
        pic = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 184, 148));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PATIENT REGISTRATION");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 66));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 118, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PatientID# :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select your State:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        add(networkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 252, 32));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 252, 32));
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 252, 33));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UserName:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 99, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        txtId.setEditable(false);
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 252, 30));
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 252, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email Address:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 118, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 252, 32));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-location.gif"))); // NOI18N
        jButton1.setText("SELECT LOCATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 169, 40));

        jButton2.setBackground(new java.awt.Color(85, 239, 196));
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 193, 33));

        jButton3.setBackground(new java.awt.Color(231, 76, 60));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 192, 33));

        snap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-camera-24.png"))); // NOI18N
        snap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapActionPerformed(evt);
            }
        });
        add(snap, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 50, 50));
        add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 140, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MapMarker map = new MapMarker();
        map.saveMapMarker(system);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:      
        if (system.getTempLocation() == null) {
            JOptionPane.showMessageDialog(this, "Please set a location", "Create fail", JOptionPane.ERROR_MESSAGE);
        }
        if (system.getUserDir().isUserUnique(txtUser.getText())) {
            Patient patient = new Patient(txtName.getText(), txtId.getText(), (Network) networkBox.getSelectedItem());
            Network n = (Network) networkBox.getSelectedItem();
            UserAccount user = new UserAccount(txtUser.getText(), txtPass.getText(), new PatientRole());
            patient.setUser(user);
            LatLong loc = system.getTempLocation();
            loc.setName(patient.getName());
            patient.setLocation(loc);
            patient.setEmail(txtEmail.getText());
            patient.setProfilePic(pic.getIcon());
            n.getPatientDirectory().getPatients().add(patient);
            system.getUserDir().getUsers().add(user);

            Email email = new Email();
            if (!isValid(txtEmail.getText())) {
                JOptionPane.showMessageDialog(this, "Invalid email", "Fail", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                email.sendEmailWithSubject(txtEmail.getText(), "Covid Care 360 Admin", "Your User Account has been created.<br>Your Patient ID#: " + txtId.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Invalid email", "Fail", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Patient Created", "Create success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Username already exists", "Create fail", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public static boolean isValid(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";
        Pattern pat = Pattern.compile(emailRegex);
        if (email == null) {
            return false;
        }
        return pat.matcher(email).matches();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.setContentPane(new LoginPanel(this.system));
        topFrame.revalidate();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void snapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapActionPerformed
        // TODO add your handling code here:
        Webcam webcam = Webcam.getDefault();
        webcam.open();
        BufferedImage image = webcam.getImage();
        ImageIcon img = new ImageIcon(image);
        Image newimg = img.getImage().getScaledInstance(140, 160, java.awt.Image.SCALE_SMOOTH);
        img = new ImageIcon(newimg);
        pic.setIcon(img);
        webcam.close();
    }//GEN-LAST:event_snapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<Network> networkBox;
    private javax.swing.JLabel pic;
    private javax.swing.JButton snap;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
